### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by jcscottiii** [18F/cf-service-connect#13]
Right now, we call out to `cf`, `mysql` and `psql` explicitly in the code. These executable names would likely only be found on unix/linux systems but not Windows.

On windows, would see names with `.exe` extensions.

**Comment by afeld** [comment]
I wonder if `cf ssh` works in Windows at all...

https://discuss.pivotal.io/hc/en-us/articles/223286048-cf-ssh-command-not-working-in-Windows

@mogul @berndverst Any idea?

**Comment by mogul** [comment]
AFAIK, it should work for Windows clients. Your link refers to using `cf ssh` to connect to apps running **on Windows hosts** (which Diego for Windows enables). We're not supporting Windows hosts/apps in cloud.gov.

**Comment by cnelson** [comment]
I just tested this on windows and it seems to work fine with no modifications.  `psql` executes fine and I can use `-no-client` to get creds to paste into GUI applications.  

![virtualbox_msedge - win10_preview_20_06_2017_08_58_16](https://user-images.githubusercontent.com/604163/27343380-8a970ba2-5597-11e7-9778-753798ab46c3.png)


Can we just add some win64 binaries to the releases and call this done?
